### ISSUE TITLE
playerStats.csv missing some matches

### ISSUE THREAD

**Issue by stephen70** [ReagentX/HLTV-Scraper#23]
playerStats.csv is missing some matches, for example the match with ID 2292366, which is present in matchResults.csv.

**Comment by ReagentX** [comment]
This is because not all matches have stats associated with them. The one you [linked](https://www.hltv.org/matches/2292703/lunatik-vs-flaming-rainbows-esea-invite-season-17-north-america), for example, has no stats. If you notice matches that have stats on HLTV but are missing from the database, please open another ticket.
