### ISSUE TITLE
Add support for individual rounds

### ISSUE THREAD

**Issue by r7cky** [ReagentX/HLTV-Scraper#24]
It would be awesome to have a rounds.csv to track matches on an individual round basis.

[Here's an example](https://github.com/r7cky/HLTVCSGOStatScanner/blob/master/HLTVCSGOStatScanner/src/com/sickpillow/helpers/HLTVHelper.java) of me getting the first round of both halves in java (slightly outdated).

And [here's the type of stuff](https://www.reddit.com/r/GlobalOffensive/comments/63xbaf/results_regarding_the_first_three_rounds_of_a_half) you can do with the data once you get it done.

**Comment by ReagentX** [comment]
To do this, parse the info inside of `<div class="standard-box round-history-con">`. Since the stats pages live at a different URL from the match page, `matchResults.csv` needs to get updated with the `mapstatsid` for each map. From there we can create a `results.csv` that has the results of every round I propose this format for the `results.csv` file:

| mapstatsid | Map | Team ID  | Round Num | End Reason |
| ------------- |-------------| -----|-----|-----|

**Comment by ReagentX** [comment]
Added in [340c613](https://github.com/ReagentX/HLTV-Scraper/commit/340c6136912e7b32ab5ff909ce513b66ec2b2286).
