### ISSUE TITLE
line break error on matchresults.csv

### ISSUE THREAD

**Issue by kpei** [ReagentX/HLTV-Scraper#6]
Line 38839, 38873 has two entries folded in one

**Comment by ReagentX** [comment]
Thanks for the report. Fixed in [da05987](https://github.com/ReagentX/HLTV-Scraper/commit/da05987d16fbaeea0c324769443fdabda1d58a9e). 

This happened when HLTV altered how dates displayed on the match pages. I corrected this in [3e5a331](https://github.com/ReagentX/HLTV-Scraper/commit/3e5a331eb210025d9d34c9144ee6772556c7b3c3), but I missed this line in the CSV. It should be fine going forward.
